# Generated by Django 6.0 on 2025-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
